Add Contact Form
ALPANNA-GH/Portfolio pull request #9
Opened 2023-06-13 22:46 UTC by ALPANNA-GH

- Create a contact form section
- Structure the form elements with `fieldset`
- Validate the inputs and make them `required`
- Styling the contact form
- Align element
- Fix some misalignment elements

2023-06-13 22:57 UTC, Zuhaib042 reviewed
Hi @ALPANNA-GH 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a failed `stylint linter`. kindly consider passing this linter before submitting again. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-13 23:07 UTC, Zuhaib042 requested changes
Hi @ALPANNA-GH 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media.giphy.com/media/4xsT7Fa4IxbMCNroH3/giphy.gif)

## Highlights
✅ Descriptive PR
✅ Professional Readme

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 23:07 UTC, Zuhaib042 commented on index.html
> +          <input class="inp" type="text" name="fullname" placeholder="Full name" required />
- [ ] Kindly consider adding `maxlength="30"` attribute here as required in the requirements.

2023-06-13 23:07 UTC, Zuhaib042 commented on index.html
> +          <textarea class="txtar" form="msgform" placeholder="write me something"></textarea>
- [ ] Kindly consider adding `maxlength= "500"` attribute here and also `required` attribute in this textarea as your form is getting submitted without it.

2023-06-13 23:07 UTC, Zuhaib042 commented on index.html
> +        <input class="submitbtn" type="submit" value="Get in touch" />
- [ ] Kindly consider styling this button color with `#E05304` while pressed using `:active` pseudoclass because this styling is required as suggested in the figma design.

2023-06-14 10:18 UTC, V-Blaze approved these changes
Hi @ALPANNA-GH  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Form submission works💯
-  Readme looks professinal👍🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 10:18 UTC, V-Blaze commented on index.html
> +      </p>
- [OPTIONAL] This wasn't pointed out by the previous reviewer, But I'll suggest you fix this before merging this pull request. 
- Currently, the margin above and below this text is bigger compared to the one in the Figma design. I'll suggest you remove the `margin` auto you add and then add the appropriate spacing and margin from the Figma design. :+1: :100: 
- I'll also suggest you adjust the text color and size to match the Figma design.

- - YOUR DESIGN:
![Selection_064](https://github.com/ALPANNA-GH/Portfolio/assets/107632780/c413e5e4-2f4b-484d-b2a9-325687651891)

- - FIGMA DESIGN:
![Screenshot from 2023-06-14 11-16-51](https://github.com/ALPANNA-GH/Portfolio/assets/107632780/e055dbd4-4507-4fd8-aeec-50644ac16f8a)

2023-06-14 10:41 UTC, merged